mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('portfolio/', include('portfolio.urls')),
]

portfolio/urls.py
from django.urls import path
from .views import IndexView, AboutView, ServicesView, PortfolioView, ContactView

app_name = 'portfolio'
urlpatterns = [
    path('', IndexView.as_view(), name='index'),
    path('about/', AboutView.as_view(), name='about'),
    path('services/', ServicesView.as_view(), name='service'),
    path('portfolio/', PortfolioView.as_view(), name='portfolio'),
    path('contact/', ContactView.as_view(), name='contact'),
]

portfolio/models.py
from django.db import models
# Create your models here.


class Contact(models.Model):
    name = models.CharField(max_length=50)
    email = models.EmailField(max_length=50)
    subject = models.CharField(max_length=50, blank=True)
    message = models.TextField()

    def __str__(self):
        return self.name


class Profile(models.Model):
    name = models.CharField(max_length=50)
    description = models.TextField()
    b_date = models.DateField()
    occupation = models.CharField(max_length=50)
    email = models.EmailField(max_length=50)
    phone = models.CharField(max_length=11)
    image = models.ImageField(upload_to='images')

    def __str__(self):
        return self.name


class Service(models.Model):
    name = models.CharField(max_length=50)
    description = models.TextField()

    def __str__(self):
        return self.name


class Client(models.Model):
    name = models.CharField(max_length=50)
    email = models.EmailField(max_length=50)
    phone = models.CharField(max_length=11)
    city = models.CharField(max_length=20)

    def __str__(self):
        return self.name


class Project(models.Model):
    name = models.CharField(max_length=50)
    description = models.TextField()
    service = models.ForeignKey(Service, on_delete=models.CASCADE)
    client = models.ForeignKey(Client, on_delete=models.CASCADE)
    date = models.DateField()
    url = models.URLField(null=True, blank=True)
    thumbnail = models.ImageField(upload_to='images')

    def __str__(self):
        return self.name

portfolio/forms.py
from django.forms import ModelForm
from .models import Contact


class ContactForm(ModelForm):
    class Meta:
        model = Contact
        fields = ['name', 'email', 'subject', 'message']

portfolio/views.py
from django.shortcuts import render
from django.views.generic.list import ListView
from django.views.generic.base import TemplateView
from django.views.generic.edit import CreateView
from django.shortcuts import get_object_or_404
from .models import Profile, Service, Project
from .forms import ContactForm
# Create your views here.


class IndexView(TemplateView):
    template_name = 'portfolio/index.html'


class AboutView(TemplateView):
    template_name = 'portfolio/about.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['profile'] = get_object_or_404(Profile, pk=1)
        return context


class ServicesView(ListView):
    model = Service
    template_name = 'portfolio/services.html'


class PortfolioView(ListView):
    model = Project
    template_name = 'portfolio/portfolio.html'

    def get_queryset(self):
        """Return the last six projects."""
        return Project.objects.order_by('-date')[:6]


class ContactView(CreateView):
    template_name = 'portfolio/contact.html'
    form_class = ContactForm
    success_url = '/thanks/'

portfolio/templates/portfolio/about.html
{% extends 'portfolio/base_about.html' %}
{% load static %}

{% block about %}
<!-- about -->
<div class="col-lg-8 m-auto">
    <h5 class="text-uppercase">About</h5>
    <h1 class="text-muted">Lorem ipsum dolor sit amet consectetur.</h1>
    <div class="row">
        <div class="col-sm-4 d-inline-block float-sm-start">
            <figure class="figure">
                <img class="figure-img img-fluid" src="{% static 'portfolio/img/5.jpg' %}" alt="..."/>
            </figure>
        </div>
        <div class="col-sm-8 container-fluid">
            <p class="text-start">Formado na área de desenvolvimento de sistemas e medalhista olímpico na modalidade "Web Design / Development" na SP Skills 2017, atuo no mercado como freelancer, oferecendo soluções completas para sistemas web, mobile, desktop, design gráfico, e sistemas integrados.</p>
        </div>
    </div>
</div>
<!-- /about -->
{% endblock about %}

portfolio/templates/portfolio/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<!--

	Author: Wellington Ideão
	Year: 2021

-->
    <head>
              <!-- Required meta tags -->
        <meta charset="UTF-8">

        <!-- mobile specific metas -->
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <!-- Bootstrap CSS -->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">

        <!-- bootstrap-social -->
        <link rel="stylesheet" href="{% static 'portfolio/css/bootstrap-social.css' %}">

        <!-- Font-Awesome -->
        <script src="https://kit.fontawesome.com/7525aea826.js" crossorigin="anonymous"></script>
        <title>{% block title %}{% endblock title %}</title>
    </head>

   <body id="page-top">
<!-- header
================================================== -->
        <header>
            <div class="container">
                <nav class="navbar navbar-expand-lg navbar-dark bg-dark" role="navegation">
                    <div class="container-fluid">
                        <a class="navbar-brand" href="">Wellington Ideão Web Developer</a>
                        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarMainMenu" aria-controls="navbarMainMenu" aria-expanded="false" aria-label="Toggle navigation">
                            <span class="navbar-toggler-icon"></span>
                        </button> <!-- /navbar-toggler -->

                         <div class="collapse navbar-collapse" id="navbarMainMenu">
                             <div class="navbar-nav text-uppercase ms-auto mb-2 mb-lg-0">
                                 <a class="nav-link active" aria-current="page" href="{% url 'portfolio:index' %}">Home</a>
                                 <a class="nav-link" href="{% url 'portfolio:about' %}">about</a>
                                 <a class="nav-link" href="{% url 'portfolio:service' %}">service</a>
                                 <a class="nav-link" href="{% url 'portfolio:portfolio' %}">portfolio</a>
                                 <a class="nav-link" href="{% url 'portfolio:contact' %}">contact</a>
                             </div><!-- /navbar-nav -->
                         </div><!-- /navbarMainMenu -->
                    </div><!-- /container-fluid -->
                </nav><!-- /nav -->
            </div><!-- /container -->
        </header><!-- /header -->

<!-- content section
================================================== -->
        <section>
            <div class="container text-center">
                {% block content %}{% endblock content %}
            </div> <!-- /container -->
        </section> <!-- /content section -->

        <!-- Option 1: Bootstrap Bundle with Popper -->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-gtEjrD/SeCtmISkJkNUaaKMoLD0//ElJ19smozuHV6z3Iehds+3Ulb9Bn9Plx0x4" crossorigin="anonymous"></script>

<!-- footer section
================================================== -->
        <footer class="py-4">
            <div class="container text-center">
                <div class="row align-items-center">
                    <div class="col-lg-4 text-lg-start">
                        Copyright © Wellington Ideão 2021
                    </div> <!-- /col -->
                    <div class="col-lg-4 my-3 my-lg-0">
                        <a class="btn btn-social-icon" href="https://www.twitter.com/">
                            <i class="fab fa-twitter"></i>
                        </a>
                         <a class="btn btn-social-icon" href="https://www.facebook.com/">
                            <i class="fab fa-facebook"></i>
                         </a>
                        <a class="btn btn-social-icon" href="https://www.linkedin.com/">
                            <i class="fab fa-linkedin"></i>
                        </a>
                    </div> <!-- /col -->
                    <div class="col-lg-4 text-lg-end">
                        <a class="link-dark text-decoration-none me-3" href="#!">Privacy Policy</a>
                        <a class="link-dark text-decoration-none" href="#!">Terms of Use</a>
                    </div> <!-- /col -->
                </div> <!-- /row -->
            </div> <!-- /container -->
        </footer> <!-- /footer section -->
   </body>
</html>

portfolio/templates/portfolio/base_about.html
{% extends 'portfolio/base.html' %}

{% block title %}ABOUT{% endblock %}
{% block content %}
<div class="row">
     {% block about %}{% endblock about %}
</div>  <!-- /row -->

{% endblock content %}

portfolio/templates/portfolio/base_contact.html
{% extends 'portfolio/base.html' %}

{% block title %}CONTACT{% endblock title %}

{% block content %}
<div class="row text-center mb-5">
    <div class="col-md-12">
     {% block header %}{% endblock header %}
    </div><!-- /col -->
</div> <!-- /row -->
<div class="row justify-content-md-center">
    <div class="col-md-6">
     {% block contact-form %}{% endblock contact-form %}
    </div><!-- /col -->
</div> <!-- /row -->
{% endblock content %}

portfolio/templates/portfolio/base_index.html
{% extends 'portfolio/base.html' %}


{% block title %}Home{% endblock title %}
{% block content %}
<div class="container pt-3 pb-5 text-align-center">
    <div class="container">
        <div class="mb-4">
            {% block sub-header %}{% endblock sub-header %}
        </div>
        <div class="mb-5">
            {% block header %}{% endblock header %}
        </div>
        {% block button %} {% endblock button %}
    </div>
</div> <!-- /container-->
{% endblock content %}

portfolio/templates/portfolio/base_portfolio.html
{% extends 'portfolio/base.html' %}

{% block title %}PORTFOLIO{% endblock title %}
{% block content %}
<div class="text-center mb-5">
     {% block header %}{% endblock header %}
</div>
<div class="row">
     {% block portfolio %}{% endblock portfolio %}
</div> <!-- /row -->
{% endblock content %}

portfolio/templates/portfolio/base_services.html
{% extends 'portfolio/base.html' %}


{% block title %}Service{% endblock title %}

{% block content %}
<div class="text-center mb-5">
    {% block header %} {% endblock header %}
</div>
<div class="row text-center">
    {% block service %} {% endblock service %}
</div> <!-- /row -->
{% endblock content %}

portfolio/templates/portfolio/contact.html
{% extends 'portfolio/base_contact.html' %}
{% load widget_tweaks %}

{% block header %}
<!-- header
================================================================= -->
<h1 class="text-uppercase">Contato</h1>
<h2 class="text-muted">Preencha o formulário abaixo para esclarecer suas dúvidas e dar início ao seu projeto.</h2><!-- /header -->
{% endblock header %}
{% block contact-form %}
<!-- contact-form
================================================================= -->
<form method="post" class="needs-validation" novalidate>
    {% csrf_token %}
        <!--{% render_field form.name class='form-control' %} -->
    <fieldset>
        {% for field in form %}
        <div class="mb-3">
            <!--<label for="{{ field.id_for_label }}" class="form-label">{{ field.label }}</label> -->
            <!-- {{ field|add_class:"form-control" }} -->
            {% render_field field class="form-control" placeholder=field.name %}
            <div class="valid-feedback">Ok!</div>
            <div class="invalid-feedback">Please choose a valid {{ field.name }}</div>
        </div>
        {% endfor %}
    </fieldset>
    <div class="d-grid">
        <button type="submit" class="btn btn-primary btn-lg">Enviar</button>
    </div>
</form> <!-- /contact-form -->
<script>
(function () {
  'use strict'

  // Fetch all the forms we want to apply custom Bootstrap validation styles to
  var forms = document.querySelectorAll('.needs-validation')

  // Loop over them and prevent submission
  Array.prototype.slice.call(forms)
    .forEach(function (form) {
      form.addEventListener('submit', function (event) {
        if (!form.checkValidity()) {
          event.preventDefault()
          event.stopPropagation()
        }

        form.classList.add('was-validated')
      }, false)
    })
})()
</script>
{% endblock contact-form %}

portfolio/templates/portfolio/index.html
{% extends 'portfolio/base_index.html' %}


{% block sub-header %}<h1>Welcome to our studio!</h1> {% endblock sub-header %}
{% block header %}<h1>IT´S NICE TO MEET YOU</h1> {% endblock header %}
{% block button %}
<a class="btn btn-primary btn-xl text-uppercase" href="{% url 'portfolio:service' %}">Tell me more</a>
{% endblock button %}

portfolio/templates/portfolio/portfolio.html
{% extends 'portfolio/base_portfolio.html' %}
{% load static %}

{% block header %}
<h1 class="text-uppercase">Portfolio</h1>
<h3 class="text-muted">Lorem ipsum dolor sit amet consectetur.</h3>
{% endblock header %}

{% block portfolio %}
<!-- Portfolio Grid
================================================== -->
{% for project in project_list %}
<div class="col-sm-6 col-lg-4 mb-4">
    {% with url_base='portfolio/img/' counter_str=forloop.counter|stringformat:'s' %}
        {% with url=url_base|add:counter_str|add:'.jpg' %}
    <!-- Portfolio item -->
        <figure class="figure">
            <a data-bs-toggle="modal" href="#portfolioModal{{project.id}}">
                <img class="figure-img img-fluid" src="{% static url %}" alt="..." />
            </a>
            <figcaption class="figure=caption">
                <h5 class="text-secondary text-capitalize">{{ project.name }}</h5>
                <div class="text-muted text-capitalize">{{project.service }}</div>
            </figcaption>
        </figure>
    <!-- /Portfolio item -->

    <!-- Portfolio Modals
    ================================================== -->
        <div class="modal fade"  id="portfolioModal{{project.id}}" tabindex="-1"  aria-labelledby="portfolioModal" aria-hidden="true">
            <div class="modal-dialog modal-dialog-centered">
                <div class="modal-content">
                    <div class="modal-body p-0 text-start">
                        <figure class="figure">
                            <a data-bs-toggle="modal" href="#portfolioModal{{project.id}}">
                                <img class="figure-img img-fluid mb-0" src="{% static url %}" alt="..." />
                            </a>
                        </figure>
                        <div class="p-4">
                            <!-- description-box -->
                            <h4 class="text-uppercase">{{project.name}}</h4>
                            <p>{{project.description}}</p>
                            <p class="text-muted text-uppercase">{{project.service}}</p>
                        </div> <!-- /description-box -->
                    </div>

                    <div class="modal-footer bg-dark ">
                        <div class="col">
                            {% if project.url %}
                                <a class="text-decoration-none text-light"  target="_blank" href="{{project.url}}" >DETALHES</a>
                            {% else %}
                                <a class="text-decoration-none text-light"  data-bs-dismiss="modal" href="#" >DETALHES</a>
                            {% endif %}
                        </div>
                        <div class="col">
                            <a class="text-decoration-none text-light" href="#" data-bs-dismiss="modal" >FECHAR</a>>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    <!-- /Portfolio Modals -->
       {% endwith %}
   {% endwith %}
</div><!-- /col-->
{% endfor %}
<!-- /Portfolio Grid-->
{% endblock portfolio %}

portfolio/templates/portfolio/services.html
{% extends 'portfolio/base_services.html' %}

{% block header %}
<h1 class="text-uppercase">Services</h1>
<h3 class="text-muted">Lorem ipsum dolor sit amet consectetur.</h3>
{% endblock header %}

{% block service %}
<div class="col-lg-4">
    <span class="fa-stack fa-2x" style="color: #1E73BE">
        <i class="fas fa-circle fa-stack-2x"></i>
        <i class="fas fa-globe-americas fa-stack-1x fa-inverse"></i>
    </span>
    <h4>Criação de Sites</h4>
    <p class="text-muted">Se você precisa de um site de qualidade, fácil de atualizar, e que caiba no seu orçamento, posso te ajudar a marcar a presença de sua empresa na internet e gerar novos negócios.</p>
</div> <!-- /col -->
<div class="col-lg-4">
    <span class="fa-stack fa-2x" style="color: #1E73BE">
        <i class="fas fa-circle fa-stack-2x"></i>
        <i class="fas fa-shopping-cart fa-stack-1x fa-inverse"></i>
    </span>
    <h4>Criação de e-commerce</h4>
    <p class="text-muted">Crio sua loja virtual, super fácil de usar, utilizando Woocommerce em WordPress a ferramenta que mais se populariza atualmente como ferramenta de vendas em e-commerce.</p>
</div> <!-- /col -->
<div class="col-lg-4">
    <span class="fa-stack fa-2x" style="color: #1E73BE">
        <i class="fas fa-circle fa-stack-2x"></i>
        <i class="fas fa-th-list fa-stack-1x fa-inverse"></i>
    </span>
    <h4>Criação de Blog</h4>
    <p class="text-muted">Para você que deseja criar um blog profissional, que ajude a melhorar seu posicionamento nos mecanismos de busca com custo acessível e qualidade.</p>
</div> <!-- /col -->
{% endblock service %}